import { NextResponse } from "next/server";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/app/_lib/auth";
import { adminAuth } from "@/app/_lib/admin";

/*Custom tokens are used to integrate Firebase Auth with existing auth systems, and must be generated by an auth backend using the createCustomToken method in the Admin SDK .*/
export async function GET() {
  /* request.ip and request.geo are available on NextRequest if deployed on vercel */
  const session = await getServerSession(authOptions);

  if (!session || !session.user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const uid = session.user.id;

  try {
    const customToken = await adminAuth.createCustomToken(uid);
    return NextResponse.json({ firebaseToken: customToken });
  } catch (error) {
    console.error("Error creating custom token:", error);
    return NextResponse.json(
      { error: "Internal Server Error" },
      { status: 500 }
    );
  }
}
